# -*- coding: utf-8 -*-
"""DWDM(rs[new]).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18EBnU64iGyUj5PIotkgRpTH2mo2i3hkx
"""

# Install required libraries (Run this only once)
!pip install wordcloud nltk scikit-learn imbalanced-learn xgboost seaborn

# Import essential libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
import re
import string
import pickle
import xgboost as xgb
from wordcloud import WordCloud
from collections import Counter
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from imblearn.over_sampling import SMOTE
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import warnings
warnings.filterwarnings('ignore')

# Download necessary NLTK datasets
nltk.download('stopwords')
nltk.download('punkt')

print("✅ Libraries Installed & Imported!")

from google.colab import files

# Upload CSV file
uploaded = files.upload()

# Get file name dynamically
file_name = list(uploaded.keys())[0]

print(f"✅ File '{file_name}' uploaded successfully!")

import pandas as pd

# Load the dataset using the uploaded filename
df = pd.read_csv(file_name)

# Remove missing values
df.dropna(inplace=True)

print("✅ Dataset Loaded! Preview:")
print(df.head())

# Install required libraries (Run this only once)
!pip install wordcloud nltk scikit-learn imbalanced-learn xgboost seaborn

# Import essential libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
import re
import string
import pickle
import xgboost as xgb
from wordcloud import WordCloud
from collections import Counter
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from imblearn.over_sampling import SMOTE
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import warnings
warnings.filterwarnings('ignore')

# Download necessary NLTK datasets
nltk.download('stopwords')
nltk.download('punkt')
# Download the punkt_tab resource
nltk.download('punkt_tab') # This line was missing

print("✅ Libraries Installed & Imported!")

from google.colab import files

# Upload CSV file
uploaded = files.upload()

# Get file name dynamically
file_name = list(uploaded.keys())[0]

print(f"✅ File '{file_name}' uploaded successfully!")

import pandas as pd

# Load the dataset using the uploaded filename
df = pd.read_csv(file_name)

# Remove missing values
df.dropna(inplace=True)

print("✅ Dataset Loaded! Preview:")
print(df.head())

print(df.head())

# Function to preprocess text
def preprocess_text(text):
    text = text.lower()  # Lowercasing
    text = re.sub(r'\d+', '', text)  # Remove numbers
    text = text.translate(str.maketrans('', '', string.punctuation))  # Remove punctuation
    text = re.sub(r'\s+', ' ', text).strip()  # Remove extra spaces
    words = word_tokenize(text)  # Tokenization
    words = [word for word in words if word not in stopwords.words('english')]  # Remove stopwords
    return " ".join(words)

# Apply preprocessing
# Replace 'resume_text' with the actual column name containing the resume text in your DataFrame.
# If you are unsure about the column names, you can print them using: print(df.columns)
df['cleaned_text'] = df['Resume'].apply(preprocess_text)  # Assuming 'Resume' is the actual column name containing the resume text.

print("✅ Text Preprocessing Completed!")

# Generate Word Cloud
wordcloud = WordCloud(width=800, height=400, background_color='black').generate(" ".join(df['cleaned_text']))

# Plot the Word Cloud
plt.figure(figsize=(10, 6))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("Word Cloud of Resume Texts")
plt.show()

print("✅ Word Cloud Generated!")

# Encode categories
label_encoder = LabelEncoder()
# Replace 'category' with the actual column name containing the categories in your DataFrame.
# If you are unsure about the column names, you can print them using: print(df.columns)
df['category_encoded'] = label_encoder.fit_transform(df['Category'])  # Assuming 'Category' is the actual column name containing the categories.

# TF-IDF Vectorization
vectorizer = TfidfVectorizer(max_features=5000)
X = vectorizer.fit_transform(df['cleaned_text'])
y = df['category_encoded']

print("✅ TF-IDF Vectorization Completed!")
print("Feature Matrix Shape:", X.shape)

# Apply SMOTE (Synthetic Minority Over-sampling)
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

print("✅ SMOTE Applied! New Data Shape:", X_resampled.shape)

# Splitting data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

print("✅ Train-Test Split Completed!")
print("Training Samples:", X_train.shape[0])
print("Testing Samples:", X_test.shape[0])

# Define base models
base_models = [
    ('random_forest', RandomForestClassifier(n_estimators=200, random_state=42)),
    ('xgboost', xgb.XGBClassifier(n_estimators=100, use_label_encoder=False, eval_metric='mlogloss'))
]

# Stacking Classifier (Combining XGBoost, Random Forest, and Logistic Regression)
stacking_model = StackingClassifier(estimators=base_models, final_estimator=LogisticRegression())

# Train the stacked model
stacking_model.fit(X_train, y_train)

print("✅ Model Training Completed!")

# Predictions on test data
y_pred = stacking_model.predict(X_test)

# Evaluation Metrics
print("✅ Model Evaluation Results:")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

# Confusion Matrix
plt.figure(figsize=(8, 6))
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

# Save the trained model
with open("resume_classifier_99.pkl", "wb") as model_file:
    pickle.dump(stacking_model, model_file)

# Save the TF-IDF vectorizer
with open("tfidf_vectorizer_99.pkl", "wb") as vectorizer_file:
    pickle.dump(vectorizer, vectorizer_file)

print("✅ Model & Vectorizer Saved Successfully!")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
from collections import Counter
import nltk
from nltk.tokenize import word_tokenize
import re
from sklearn.feature_extraction.text import TfidfVectorizer

plt.figure(figsize=(12, 6))
sns.countplot(y=df['Category'], order=df['Category'].value_counts().index, palette='coolwarm')
plt.title("Number of Resumes per Category", fontsize=14)
plt.xlabel("Count")
plt.ylabel("Category")
plt.show()

text = " ".join(df['cleaned_text'])
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.title("Most Frequent Words in Resumes", fontsize=14)
plt.show()

all_words = " ".join(df['cleaned_text']).split()
word_freq = Counter(all_words)

top_words = dict(word_freq.most_common(20))

plt.figure(figsize=(12, 6))
sns.barplot(x=list(top_words.values()), y=list(top_words.keys()), palette="viridis")
plt.title("Top 20 Most Frequent Words in Resumes", fontsize=14)
plt.xlabel("Frequency")
plt.ylabel("Words")
plt.show()

vectorizer = TfidfVectorizer(max_features=20)  # Extract top 20 important words
tfidf_matrix = vectorizer.fit_transform(df['cleaned_text'])
feature_names = vectorizer.get_feature_names_out()
importance = tfidf_matrix.sum(axis=0).A1

tfidf_df = pd.DataFrame({'Feature': feature_names, 'Importance': importance})
tfidf_df = tfidf_df.sort_values(by='Importance', ascending=False)

plt.figure(figsize=(12, 6))
sns.barplot(x=tfidf_df['Importance'], y=tfidf_df['Feature'], palette="magma")
plt.title("Top 20 Important Words Based on TF-IDF Scores", fontsize=14)
plt.xlabel("TF-IDF Score")
plt.ylabel("Words")
plt.show()

df['resume_length'] = df['cleaned_text'].apply(lambda x: len(x.split()))

plt.figure(figsize=(10, 5))
sns.histplot(df['resume_length'], bins=30, kde=True, color='green')
plt.title("Distribution of Resume Length", fontsize=14)
plt.xlabel("Number of Words")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(12, 6))
sns.boxplot(x=df['Category'], y=df['resume_length'], palette="coolwarm")
plt.xticks(rotation=90)
plt.title("Resume Length Distribution by Category", fontsize=14)
plt.xlabel("Category")
plt.ylabel("Number of Words")
plt.show()

from nltk.util import ngrams
import itertools

def get_bigrams(text):
    tokens = word_tokenize(text)
    return list(ngrams(tokens, 2))

bigrams_list = list(itertools.chain(*df['cleaned_text'].apply(get_bigrams)))
bigram_freq = Counter(bigrams_list).most_common(20)

bigram_words = [" ".join(bigram) for bigram, _ in bigram_freq]
bigram_counts = [count for _, count in bigram_freq]

plt.figure(figsize=(12, 6))
sns.barplot(x=bigram_counts, y=bigram_words, palette="rocket")
plt.title("Top 20 Most Common Bigrams", fontsize=14)
plt.xlabel("Frequency")
plt.ylabel("Bigram Words")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Select only numeric features for correlation
numeric_df = df.select_dtypes(include=['number'])  # Selects only numeric columns

plt.figure(figsize=(10, 5))
sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap", fontsize=14)
plt.show()

!pip install pandas numpy scikit-learn xgboost nltk transformers sentence-transformers

import pandas as pd
import numpy as np
import re
import nltk
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report
from sentence_transformers import SentenceTransformer
import matplotlib.pyplot as plt
import seaborn as sns

# Download necessary NLTK resources
nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")

from google.colab import files

# Upload CSV file
uploaded = files.upload()

# Get file name dynamically
file_name = list(uploaded.keys())[0]

print(f"✅ File '{file_name}' uploaded successfully!")

import pandas as pd

# Load the dataset using the uploaded filename
df = pd.read_csv(file_name)

# Remove missing values
df.dropna(inplace=True)

print("✅ Dataset Loaded! Preview:")
print(df.head())

# Check for missing values
print("\nMissing Values:\n", df.isnull().sum())

# Check unique categories
print("\nCategories in Dataset:", df["Category"].unique())

def preprocess_text(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'\d+', '', text)  # Remove numbers
    text = text.translate(str.maketrans("", "", string.punctuation))  # Remove punctuation
    tokens = word_tokenize(text)  # Tokenization
    tokens = [WordNetLemmatizer().lemmatize(word) for word in tokens if word not in stopwords.words("english")]  # Lemmatization & Stopwords removal
    return " ".join(tokens)

df["cleaned_text"] = df["Resume"].apply(preprocess_text)
print("\n✅ Text Preprocessing Completed!")

# Install required libraries (Run this only once)
!pip install wordcloud nltk scikit-learn imbalanced-learn xgboost seaborn

# Import essential libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
import re
import string
import pickle
import xgboost as xgb
from wordcloud import WordCloud
from collections import Counter
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from imblearn.over_sampling import SMOTE
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import warnings
warnings.filterwarnings('ignore')

# Download necessary NLTK datasets
nltk.download('stopwords')
nltk.download('punkt')
# Download the punkt_tab resource
nltk.download('punkt_tab') # This line was missing

print("✅ Libraries Installed & Imported!")

plt.figure(figsize=(10, 5))
sns.countplot(x=df["Category"], order=df["Category"].value_counts().index, palette="viridis")
plt.xticks(rotation=45)
plt.title("Distribution of Resume Categories")
plt.show()

bert_model = SentenceTransformer("paraphrase-MiniLM-L3-v2")
  # Lightweight BERT model for embeddings
X = bert_model.encode(df["cleaned_text"])
y = df["Category"]
print("\n✅ Feature Extraction with BERT Completed!")

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("\n✅ Train-Test Split Done!")

from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder object
label_encoder = LabelEncoder()

# Fit the encoder to your training target variable
label_encoder.fit(y_train)

# Transform both training and testing target variables
y_train_encoded = label_encoder.transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# Now, use the encoded target variables for training and evaluation
xgb_model = XGBClassifier(n_estimators=70, learning_rate=0.1, max_depth=4, random_state=42)
xgb_model.fit(X_train, y_train_encoded) # Use encoded y_train
print("\n✅ Model Training Completed!")

# For predictions, remember to use the encoded test data:
y_pred = xgb_model.predict(X_test)

# And to get the original category labels back, use inverse_transform:
y_pred_original = label_encoder.inverse_transform(y_pred)

print("X_train type:", type(X_train))
print("X_train shape:", X_train.shape)
print("y_train type:", type(y_train))
print("y_train unique values:", np.unique(y_train))

import numpy as np
X_train = np.array(X_train)
X_test = np.array(X_test)

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)
y_test = label_encoder.transform(y_test)

from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=70,
    learning_rate=0.1,
    max_depth=4,
    subsample=0.85,
    colsample_bytree=0.85,
    random_state=42
)
xgb_model.fit(X_train, y_train)


print("\n✅ Model Training Completed!")

y_pred = xgb_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print(f"\n🎯 Accuracy: {accuracy * 100:.2f}%")
print("\n🔍 Classification Report:\n", classification_report(y_test, y_pred))

import pickle

# Save trained model
with open("resume_classifier.pkl", "wb") as model_file:
    pickle.dump(xgb_model, model_file)

# Save BERT model (optional)
with open("bert_model.pkl", "wb") as bert_file:
    pickle.dump(bert_model, bert_file)

print("\n✅ Model Saved Successfully!")

# Load saved model
with open("resume_classifier.pkl", "rb") as model_file:
    loaded_model = pickle.load(model_file)

# Load BERT model
with open("bert_model.pkl", "rb") as bert_file:
    loaded_bert = pickle.load(bert_file)

# Test with a new resume
new_resume = ["I have experience in Python, machine learning, and deep learning. Worked on AI models and cloud computing."]
new_resume_vectorized = loaded_bert.encode(new_resume)

# Predict category
predicted_category = loaded_model.predict(new_resume_vectorized)
print("\n📢 Predicted Resume Category:", predicted_category[0])

plt.figure(figsize=(8, 6))
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(20,5))
plt.xticks(rotation=90)
# Replace 'resumeDataSet' with 'df'
ax=sns.countplot(x="Category", data=df)
for p in ax.patches:
    ax.annotate(str(p.get_height()), (p.get_x() * 1.01 , p.get_height() * 1.01))
plt.grid()

from matplotlib.gridspec import GridSpec
# Replace 'resumeDataSet' with 'df'
targetCounts = df['Category'].value_counts()
targetLabels  = df['Category'].unique()
# Make square figures and axes
plt.figure(1, figsize=(22,22))
the_grid = GridSpec(2, 2)


cmap = plt.get_cmap('coolwarm')
plt.subplot(the_grid[0, 1], aspect=1, title='CATEGORY DISTRIBUTION')

source_pie = plt.pie(targetCounts, labels=targetLabels, autopct='%1.1f%%', shadow=True)
plt.show()

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder # Import LabelEncoder

# Assuming y_train contains your original target variable labels
le = LabelEncoder() # Create a LabelEncoder object
le.fit(y_train) # Fit it to your training data

cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(12, 8))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=le.classes_, yticklabels=le.classes_)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

# ... (your existing code)

# Load the TF-IDF vectorizer used during training
with open("tfidf_vectorizer_99.pkl", "rb") as vectorizer_file:
    vectorizer = pickle.load(vectorizer_file)

# Transform your new data using the loaded vectorizer
X_test_tfidf = vectorizer.transform(df['cleaned_text'])  # Use 'cleaned_text' from your df

# Now use X_test_tfidf for prediction
y_pred = stacking_model.predict(X_test_tfidf)

# ... (your existing code)

# After extracting BERT embeddings:

# Splitting data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # X is your BERT embeddings

# Define base models (you might need to adjust hyperparameters)
base_models = [
    ('random_forest', RandomForestClassifier(n_estimators=200, random_state=42)),
    ('xgboost', xgb.XGBClassifier(n_estimators=100, use_label_encoder=False, eval_metric='mlogloss'))
]

# Stacking Classifier
stacking_model = StackingClassifier(estimators=base_models, final_estimator=LogisticRegression())

# Train the stacked model with BERT features
stacking_model.fit(X_train, y_train)

# Now you can use X_test (BERT embeddings) for prediction
y_pred = stacking_model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Predict using the trained model
y_pred = stacking_model.predict(X_test)

# Print evaluation results
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))